### ISSUE TITLE
Singleton change / issues

### ISSUE THREAD

**Issue by jods4** [aurelia/dependency-injection#58]
Two releases ago, I had ViewModel caching / reuse (to preserve user state accross navigation) working by putting `@singleton(false)` on top of my ViewModels.

Since updating to current Aurelia release, it doesn't work anymore.

Did something change or break in the API? How should I currently tell Aurelia to re-use my ViewModels?

Hooking the debugger shows that although there is the `@singleton(false)` decoration, my ctor gets called everytime (-> new instance).

**Comment by EisenbergEffect** [comment]
I'll check this out myself.

**Comment by EisenbergEffect** [comment]
Confirmed that placing `singleton()` on a view model works as expected, at least in the master.

**Comment by jods4** [comment]
Do you have an example? 

Placing `@singleton()` or `@singleton(false)`? because a few releases ago it was `@singleton(false)`.

Any idea what could influence this? Because it definitely does not work in my code base on current release and I'm 100% sure it previously did.

**Comment by jods4** [comment]
I am pretty sure it does not work -- or I don't understand how it's intended to work.

I have done some debugging and it seems the breaking change is here:
https://github.com/aurelia/dependency-injection/commit/5e2b75b21d20c2f54d277ccbaf147de8c2ce5e74#diff-dcf9a6cedb6d0d9a360cc92ddaa1c0c2L52

Before commit #5e2b75b, the singleton `createResolver` used to return a root singleton when `registerInChild` was false and such a singleton already existed. 
After the change, a new resolver is always created an returned. It is then registered at root (kinda) but that doesn't really matter... the already existing singleton resolver at root is not returned.

I think that's why my view are recreated every time.

**Comment by nomack84** [comment]
@jods4 Today will probably by a pre-betarelease, perhaps is solved here

**Comment by jods4** [comment]
Maybe, but doubtful as the sources I was looking at are `master` and they don't seem fundamentally different from what I'm running.

If there's a pre-beta release coming, I think this should be double-checked ASAP before the release because it's a major bug, that's worthy of being fixed for that release.

**Comment by EisenbergEffect** [comment]
There was a bug in the DI in the last released. It has been fixed. I tested this myself by simply placing `@singleton()` on the welcome view model in the navigation-skeleton app.

**Comment by jods4** [comment]
Can you refer the fixing commit? I need to patch this today.

**Comment by EisenbergEffect** [comment]
https://github.com/aurelia/dependency-injection/commit/ca5ccf7d03e907ce9fb794dcbe9f0065ceba3c43#diff-dcf9a6cedb6d0d9a360cc92ddaa1c0c2R94

Getting the latest master will require the latest of metadata also...but that is going to break everything else. So, just wait for a little bit. We are going to try to get a pre-beta release out today.

**Comment by jods4** [comment]
I managed to patch around this bug but I had to do it a very ugly way. When I tried to apply the changes you linked above, the result was still the same (i.e. not reusing the same VM for the whole app). But maybe that was because I was missing other relevant bits.

I'll test with the new release and report if it doesn't work.
